.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "DEBUG" "1" "February 2016" "" "debug"
.
.SH "NAME"
\fBdebug\fR \- Conditional debug logger
.
.SH "SYNOPSIS"
\fBdebug\fR \fIstring\fR [\fIarguments\fR \.\.\.] [\-\-header=\fIformat\fR] [\-\-footer=\fIformat\fR] [\-\-no\-color] [\-\-help]
.
.br
.
.SH "DESCRIPTION"
\fBDebug\fR is a conditional logger for fish\. Use it to instrument your programs and find bottlenecks\.
.
.SH "OPTIONS"
.
.TP
\-\-header=\fIformat\fR
Set header format\. See \fIFormat\fR for details\.
.
.TP
\-\-footer=\fIformat\fR
Set header format\. See \fIFormat\fR for details\.
.
.TP
\-\-no\-color
Turn off color output\.
.
.TP
\-h, \-\-help
Display usage help\.
.
.SH "USAGE"
Log visibility is off by default\. To make all logs visible
.
.IP "" 4
.
.nf

set \-g fish_debug "*"
.
.fi
.
.IP "" 0
.
.P
or filter specific functions
.
.IP "" 4
.
.nf

set \-g fish_debug "my_function1" "my_function2" "!my_function3"
.
.fi
.
.IP "" 0
.
.P
To use it in your program, call debug \fIstring\fR [\fIarguments\.\.\.\fR]\. \fIString\fR can be any valid [printf(1)] format string with \fIarguments\fR\.
.
.IP "" 4
.
.nf

function download \-a url
    debug "Download start %s" $url
    sleep 1
    debug "Download complete"
end
.
.fi
.
.IP "" 0
.
.IP "" 4
.
.nf

$ download https://github\.com/fishery/debug
download Download start https://github\.com/fishery/debug 0ms
download Download complete 1s 24ms
.
.fi
.
.IP "" 0
.
.P
Debug formats logs in three parts, \fIheader\fR, \fIbody\fR and \fIfooter\fR\.
.
.IP "" 4
.
.nf

header body footer
.
.fi
.
.IP "" 0
.
.IP "\(bu" 4
\fIheader\fR is the name of the function where debug was called,
.
.IP "\(bu" 4
\fIbody\fR is a \fIstring\fR with optional \fIarguments\fR and
.
.IP "\(bu" 4
\fIfooter\fR is the elapsed time between the current and last debug call\.
.
.IP "" 0
.
.P
Use \-\-header=\fIformat\fR and \-\-footer=\fIformat\fR to customize their format\.
.
.SS "FORMAT"
Debug is context aware and recognizes the following \fB%\fR placeholders:
.
.IP "\(bu" 4
\fI%name\fR, the name of the function or file where debug was used, or \fB@\fR if called in the command line\.
.
.IP "\(bu" 4
\fI%line\fR, the line number where debug was used\.
.
.IP "\(bu" 4
\fI%file\fR, the full path to the file where debug was used\.
.
.IP "" 0
.
.P
For example, to display the time in the \fIheader\fR and name in the \fIfooter\fR you can do the following\.
.
.IP "" 4
.
.nf

function download \-a url
    debug \-\-header="%time" \-\-footer="(%name)" "Download start %s" $url
    sleep 1
    debug \-\-header="%time" \-\-footer="(%name)" "Download complete"
end
.
.fi
.
.IP "" 0
.
.IP "" 4
.
.nf

0ms Download start https://github\.com/fishery/debug (download)
1s 45ms Download complete (download)
.
.fi
.
.IP "" 0
.
.SS "COLORS"
Debug colorizes function names with a random color, but assigns the same color to functions of the same name for visibility\. To turn off color output use \-\-no\-color\.
