.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SPIN" "1" "February 2016" "" "spin"
.
.SH "NAME"
\fBspin\fR \- Spin a background job
.
.SH "SYNOPSIS"
\fBspin\fR \fIcommands\fR [\fB\-\-style\fR=\fImix\fR|\fIarc\fR|\fIstar\fR|\fIpipe\fR|\fIflip\fR|\fIbounce\fR|\fIbar1~3\fR]
.
.br
\fBspin\fR \fIcommands\fR [\fB\-\-error\fR=file] [\fB\-\-format\fR=format] [\fB\-\-help\fR]
.
.SH "DESCRIPTION"
\fBSpin\fR is a terminal spinner and progress bar indicator for fish\.
.
.SH "USAGE"
Run one or more commands and set the spinner style using \fB\-\-style=<style>\fR\.
.
.IP "" 4
.
.nf

for spin in mix arc star pipe flip bounce
    spin "sleep 1" \-\-style=$spin
end
.
.fi
.
.IP "" 0
.
.P
Use \fB\-\-style=bar{1,2,3}\fR to display a progress bar\.
.
.IP "" 4
.
.nf

for bar in bar{1,2,3}
    spin "sleep 1" \-\-style=$bar
end
.
.fi
.
.IP "" 0
.
.P
There is currently [\fIno\fR][lack\-of\-wait] reliable mechanism to determine the exit status of a process running in the background\. As a work around, any output to standard error is used to determine failure\. Use \fB\-\-error=<file>\fR to redirect the standard error output to \fBfile\fR\.
.
.IP "" 4
.
.nf

if not spin \-\-style=pipe \-\-error=debug\.txt "curl \-sS $URL"
    return 1
end
.
.fi
.
.IP "" 0
.
.SH "OPTIONS"
.
.TP
\fB\-s \-\-style=style|string\fR
Set the spinner style\. See \fBStyles\fR for styles and details on how to customize the spinner tokens\.
.
.TP
\fB\-f \-\-format=format\fR
Use the given \fIformat\fR to display the spinner\. The default format is \fB"\er@"\fR where \fB@\fR represents the spinner token and \fB\er\fR a carriage return, used to refresh (erase) the line\.
.
.TP
\fB\-\-error=file\fR
Write the standard error output to a given \fIfile\fR\.
.
.TP
\fB\-h \-\-help\fR
Show usage help\.
.
.SH "STYLES"
The following spinner styles are available with \fB\-\-style=<style>\fR\.
.
.IP "\(bu" 4
mix, arc, star, pipe, flip, mix, bounce
.
.IP "\(bu" 4
bar1~3
.
.IP "" 0
.
.P
If no style is given, \fBmix\fR is used by default\. If you don\'t want to display any spinners, use \fB\-\-style=""\fR\.
.
.SS "CUSTOMIZATION"
In addition to the default styles, you can specify the string of characters that will be used per refresh cycle to show the spinner\.
.
.P
For example \fB\-\-style=12345\fR will display the numbers from 1 to 5, and \fB\-\-style=\. \-\-format=@\fR an increasing sequence of dots\.
.
.SS "PROGRESS BARS"
Display a progress bar with a percent indicator using \fB\-\-style=bar1~3\fR:
.
.IP "\(bu" 4
bar1: \fB[==============] 100%\fR
.
.IP "\(bu" 4
bar2: \fB[##############] 100%\fR
.
.IP "\(bu" 4
bar3: \fB\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\. 100%\fR
.
.IP "" 0

