(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(TeX-output-view-style (quote (("^dvi$" ("^landscape$" "^pstricks$\\|^pst-\\|^psfrag$") "%(o?)dvips -t landscape %d -o && gv %f") ("^dvi$" "^pstricks$\\|^pst-\\|^psfrag$" "%(o?)dvips %d -o && gv %f") ("^dvi$" ("^a4\\(?:dutch\\|paper\\|wide\\)\\|sem-a4$" "^landscape$") "%(o?)xdvi %dS -paper a4r -s 0 %d") ("^dvi$" "^a4\\(?:dutch\\|paper\\|wide\\)\\|sem-a4$" "%(o?)xdvi %dS -paper a4 %d") ("^dvi$" ("^a5\\(?:comb\\|paper\\)$" "^landscape$") "%(o?)xdvi %dS -paper a5r -s 0 %d") ("^dvi$" "^a5\\(?:comb\\|paper\\)$" "%(o?)xdvi %dS -paper a5 %d") ("^dvi$" "^b5paper$" "%(o?)xdvi %dS -paper b5 %d") ("^dvi$" "^letterpaper$" "%(o?)xdvi %dS -paper us %d") ("^dvi$" "^legalpaper$" "%(o?)xdvi %dS -paper legal %d") ("^dvi$" "^executivepaper$" "%(o?)xdvi %dS -paper 7.25x10.5in %d") ("^dvi$" "." "%(o?)xdvi %dS %d") ("^pdf$" "." "evince %o %(outpage)") ("^html?$" "." "netscape %o"))))
 '(ack-and-a-half-arguments nil)
 '(ack-and-a-half-executable "/usr/local/bin/ag")
 '(before-save-hook (quote (time-stamp delete-trailing-whitespace)))
 '(browse-url-browser-function (quote browse-url-generic))
 '(browse-url-firefox-new-window-is-tab nil)
 '(browse-url-firefox-program "firefox")
 '(browse-url-generic-program "open")
 '(browse-url-mozilla-program "mozilla")
 '(column-number-mode t)
 '(completion-use-popup-frame nil)
 '(cua-rectangle-mark-key (kbd "<C-S-return>"))
 '(custom-safe-themes (quote ("71b172ea4aad108801421cc5251edb6c792f3adbaecfa1c52e94e3d99634dee7" default)))
 '(display-time-mode nil)
 '(doxymacs-file-comment-template (quote ("/**" > n " * " (doxymacs-doxygen-command-char) "file   " (if (buffer-file-name) (file-name-nondirectory (buffer-file-name)) "") > n " * " (doxymacs-doxygen-command-char) "author " (user-full-name) (doxymacs-user-mail-address) > n " * " (doxymacs-doxygen-command-char) "date   Time-stamp: <>" > n " * " > n " * " (doxymacs-doxygen-command-char) "brief  " (p "Brief description of this file: ") > n " * " > n " * " p > n " */" > n)))
 '(ecb-auto-activate nil)
 '(ecb-layout-name "left4")
 '(ecb-options-version "2.40")
 '(ecb-source-path (quote (("~/proj/" "Projects"))))
 '(ecb-tree-buffer-style (quote ascii-guides))
 '(ecb-tree-indent 2)
 '(erc-user-full-name "Nagy Zoltán")
 '(face-font-family-alternatives (quote (("arial black" "arial" "DejaVu Sans") ("arial" "DejaVu Sans") ("verdana" "DejaVu Sans"))))
 '(font-lock-keywords-case-fold-search t t)
 '(global-font-lock-mode t nil (font-lock))
 '(grep-command "ag --nogroup --column -S ")
 '(haskell-literate-default (quote tex))
 '(haskell-mode-hook (quote (turn-on-haskell-indent turn-on-haskell-indentation turn-on-haskell-doc-mode)))
 '(haskell-program-name "/usr/local/bin/ghci \"+.\"")
 '(helm-idle-delay 0.3)
 '(helm-input-idle-delay 0.3)
 '(helm-never-delay-on-input t)
 '(helm-quick-update t)
 '(imenu-auto-rescan t)
 '(imenu-auto-rescan-maxout 60000000)
 '(inhibit-startup-screen t)
 '(jde-enable-abbrev-mode t)
 '(js-indent-level 2)
 '(mediawiki-site-alist (quote (("Wikipedia" "http://en.wikipedia.org/w/" "username" "password" "Main Page") ("Prezi Wiki" "http://wiki.prezi.com/w/" "zoltan.nagy@prezi.com" "foobar" "Main Page"))))
 '(mumamo-noweb2-mode-from-ext (quote (("c" . c-mode))))
 '(mumamo-set-major-mode-delay 0.3)
 '(nuke-trailing-whitespace-p t)
 '(nxhtml-default-encoding (quote utf-8))
 '(nxhtml-skip-welcome t)
 '(nxml-mode-hook (quote (rng-validate-mode)))
 '(org-agenda-files (quote ("~/proj/beluga/proj.org" "~/gtd/main.org")))
 '(org-export-author-info nil)
 '(org-export-creator-info nil)
 '(org-export-default-language "hu")
 '(org-export-preserve-breaks t)
 '(org-export-time-stamp-file nil)
 '(php-manual-path "~/docs/php/html")
 '(ruby-deep-arglist nil)
 '(scala-indent:step 4)
 '(shell-file-name "/usr/local/bin/zsh")
 '(show-paren-mode t)
 '(show-paren-style (quote mixed))
 '(show-trailing-whitespace t)
 '(smooth-scroll-margin 4)
 '(tabbar-mode nil)
 '(time-stamp-format "%:y-%02m-%02d %02H:%02M:%02S")
 '(twit-minor-mode t)
 '(twit-pass "nzpd2004")
 '(twit-protocol "https")
 '(twit-show-user-images nil)
 '(twit-user "abesto")
 '(twit-user-image-dir "~/.emacs.d//twitter-images")
 '(uniquify-buffer-name-style (quote post-forward-angle-brackets) nil (uniquify))
 '(use-file-dialog nil)
 '(weblogger-config-alist (quote (("new" "http://abesto.net/textpattern/rpc/" "abesto" "" "articles") ("abesto.net" "http://abesto.net/rpc/" "abesto" "" "articles") ("abesto.net/articles" "http://abesto.net/tp/rpc/" "abesto" "" "articles"))))
 '(weblogger-edit-entry-hook nil)
 '(weblogger-pre-struct-hook (quote ((lambda nil (message-remove-header "X-TextType") (message-add-header "X-TextType: USE_TEXTILE")))))
 '(weblogger-start-edit-entry-hook (quote ((lambda nil (message-goto-body) (while (search-forward "" nil t) (replace-match "" nil t))) (lambda nil (auto-fill-mode 0) (longlines-mode 1)))))
 '(windmove-wrap-around nil)
 '(yas/prompt-functions (quote (yas/dropdown-prompt yas/completing-prompt yas/ido-prompt yas/no-prompt))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
